
name: vunit

on:
  push:
  pull_request:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: VUnit/vunit_action@master
      with:
        cmd: ./run.py
